version: 1
groups:
  - annotation: ckanext-nswdesignsystem
    options:
      - key: ckanext.nswdesignsystem.debug
        type: bool
      - key: ckanext.nswdesignsystem.css_enabled
        type: bool
        default: true
      - key: ckanext.nswdesignsystem.js_enabled
        type: bool
        default: true
